### ISSUE TITLE
[1.0.rc-1] Group/Segregate ado sub commands

### ISSUE THREAD

**Issue by SlayerAnsh** [andromedaprotocol/andromeda.js#105]
**Describe the bug**
Currently `ado` command has 10+ commands but not all of them are ado specific. It would be nice to group these commands into separate handle. 

Suggested Commands Grouping ( All commands are listed relative to root command)
- `os` => vfs commands, db command. Also Add kernel command for easy kernel query
-  `ado -> base` => Base ado commands like transfer ownership, accept ownership,  etc
- `ado -> ...rest` of the commands remain in same position like execute, query, instantiate.

**Expected behavior**
A clear grouping and flow of execution will help in navigating through cli commands easily

**Comment by crnbarr93** [comment]
We can maybe group stuff like ownership and permissioning under individual subcommands?
