### ISSUE TITLE
Extension query in CW721

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#49]
Running ado query, then selecting the extension query runs for a while then crashes the CLI with error:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by crnbarr93** [comment]
This particular error was caused by a circular dependency within the schema for the `Extension` query as the query itself wanted a `QueryMsg` which included `Extension` and so on.
