### ISSUE TITLE
Aprroval and Approvals queries not found when running ado query

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#50]
The Approval and Approvals queries on a CW721 are not listed with ado query.

**Comment by daniel-wehbe** [comment]
Seems that the queries are not found when trying to call them as I am getting the following error:
unknown variant `approval`
Although they are found in the contract.

**Comment by crnbarr93** [comment]
Missing within the contract

**Comment by crnbarr93** [comment]
Added to contracts and updated schema references to use the new schemas
