### ISSUE TITLE
Passphrase Mismatch Fault

### ISSUE THREAD

**Issue by leifasorensen** [andromedaprotocol/andromeda.js#51]
## Prompting failure on passphrase mismatch
When trying for `wallet add` prompt: failing to correctly enter the same passphrase triggers a passphrase mismatch warning, but also halts prompting and the CLI is required to be reset.

![Screenshot 2023-02-09 at 8 57 05 AM](https://user-images.githubusercontent.com/60895101/217832748-cb0386eb-1cec-43cf-8f31-6f078920b01d.png)

**Comment by crnbarr93** [comment]
Working as intended, passphrase is hidden but input is still there
