### ISSUE TITLE
Infinite Prompt for Modules 

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#52]
When prompted " would you like to add module" for cases where modules can be added, if you input yes, you are never asked if you want to add another module but it keeps prompting the same fields. 
<img width="1139" alt="Screen Shot 2023-02-15 at 7 21 27 PM" src="https://user-images.githubusercontent.com/90905690/219105458-000fa427-2cdf-4404-af42-e51a799d987f.png">

**Comment by crnbarr93** [comment]
Added escape clause after adding one field in optional array
