### ISSUE TITLE
Error when executing SetValue on a primitive

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#53]
When I run ado execute on a primitive and then select the Set Value execute, the CLI runs for a while then aborts with the following error: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

<img width="1130" alt="Screen Shot 2023-02-19 at 5 34 25 PM" src="https://user-images.githubusercontent.com/90905690/219958128-171633d7-b28a-4b6c-a370-cc949a7609a9.png">

**Comment by crnbarr93** [comment]
Resolved with #49
