### ISSUE TITLE
Help Command for Base Commands

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#54]
Running --help next to a base command does not list the available commands as it used to. 
<img width="698" alt="Screen Shot 2023-02-21 at 3 25 40 PM" src="https://user-images.githubusercontent.com/90905690/220356969-1d2cbe23-4b17-4a56-a6c1-15352601252f.png">

**Comment by daniel-wehbe** [comment]
Also for commands like "ado db --help" , does not list.

**Comment by crnbarr93** [comment]
Added the command list table to the help flag
