### ISSUE TITLE
Cannot exit Command: chain new (After first field) 

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#56]
If we run "chain new"  we can exit the prompt in the first field (Config name) but not other fields:
<img width="698" alt="Screen Shot 2023-02-21 at 4 12 32 PM" src="https://user-images.githubusercontent.com/90905690/220369155-96f36ed8-a294-4bf0-ae5b-8172bebe6809.png">

**Comment by daniel-wehbe** [comment]
One more note here, as you can see above even if the gas price is invalid, the config is still created. Not sure if we want that or not.

**Comment by crnbarr93** [comment]
Added input Regex for this and chain URL
