### ISSUE TITLE
GET WALLET when connecting to injective

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#62]
When we connect to injective or change wallets in injective, "GET WALLET" is displayed twice: 
<img width="354" alt="Screen Shot 2023-02-27 at 12 07 40 PM" src="https://user-images.githubusercontent.com/90905690/221534974-de364d24-6cee-4d99-a2af-88c5c564463b.png">

**Comment by crnbarr93** [comment]
Removed in recent version
