### ISSUE TITLE
Gas Fee Estimation

### ISSUE THREAD

**Issue by crnbarr93** [andromedaprotocol/andromeda.js#63]
Andromeda Client using incorrect GasPrice value, gas fee estimate must match the broadcast cost approximately

**Comment by leifasorensen** [comment]
@crnbarr93 If this is still an issue then could you provide further clarification?

**Comment by crnbarr93** [comment]
This is an oldie, but our gas fee estimation wasn't matching up to Keplr. If it's correct on the webapp I'd guess it's fixed.

**Comment by leifasorensen** [comment]
We performed some base testing and found that current estimations seem to have an approximation accuracy within a tolerable range of variance. Exceptionally large transactions may show the discrepancy, but does not appear to be generally problematic at this time.

We have added a few notes for tracking possible improvements which can be addressed in future updates. I am closing this issue as I believe it has been addressed to satisfactory levels.
