### ISSUE TITLE
ado execute prompts

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#66]
when we run ado execute and select a message, we are prompted for the message above the selected one. For example if I select TransferNFT from the CW721 messages, I am prompted for a mint since it is above it in the options.

**Comment by crnbarr93** [comment]
Cannot replicate this on 0.3.1, can you confirm if it is still occuring?

**Comment by leifasorensen** [comment]
I also can confirm that this is working as intended in ver 0.3.8. I will close the task and it can be reopened if encountered again.

![transfer nft menu selection](https://github.com/andromedaprotocol/andromeda.js/assets/60895101/a4f699c7-5a25-46df-8f93-41ebd124b036)
