### ISSUE TITLE
Gas Price error when running a bank send (transferring funds to another address)

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#70]
Trying to send funds to another address is giving the following error: Gas price must be set in the client options when auto gas is used.
<img width="921" alt="Screen Shot 2023-04-26 at 3 07 12 PM" src="https://user-images.githubusercontent.com/90905690/234571226-90dd7c5f-0cf7-4183-a6a5-f30da56153b6.png">

**Comment by crnbarr93** [comment]
Cannot replicate this on 0.3.1, can you confirm if it is still occuring?

**Comment by leifasorensen** [comment]
I have also confirmed this is working as intended in v0.3.8. I will close this issue, and it can be reopened if encountered again.

![bank send conflict](https://github.com/andromedaprotocol/andromeda.js/assets/60895101/0a00b7a9-3150-4963-9e2a-b910a5d06fd5)
