### ISSUE TITLE
Wallet Input Passphrase Disclosed

### ISSUE THREAD

**Issue by leifasorensen** [andromedaprotocol/andromeda.js#71]
## Issue
When adding a wallet, part of the process requires inputing a passphrase into a hidden field. The output line which appears between it and the re-prompt prints the entered value (which should be private) to the terminal.

In this example (below) the passphrase of "disclosed" is visible.

### Example
![Screenshot 2023-04-26 at 9 48 03 PM](https://user-images.githubusercontent.com/60895101/234740228-1d448779-3a60-4aed-a96f-dbab9a2f761e.png)

### Version Info
ANDR.JS CLI 0.2.5
NodeJS 18.14.0

**Comment by crnbarr93** [comment]
Should be resolved in 0.3.0+
