### ISSUE TITLE
Uploading a contract to injective

### ISSUE THREAD

**Issue by daniel-wehbe** [andromedaprotocol/andromeda.js#77]
Getting the following error: Transaction was not included in a block before timeout of 60000ms
This is probably a problem from the injective side, but put an issue to keep track of it.
<img width="1036" alt="Screen Shot 2023-07-19 at 5 51 22 PM" src="https://github.com/andromedaprotocol/andromeda.js/assets/90905690/c278064d-dd1b-4313-9aed-bec9bf3e58b6">

**Comment by leifasorensen** [comment]
Yes, there were some problems which had occurred after a chain update which were creating broadcast conflicts with Injective. These were addressed at that time. We are roadmapped for further Injective support coming in future, and will be addressing any injective specific issues at that time.

I am closing this task as resolved.
