### ISSUE TITLE
Default values for Bank Balance query

### ISSUE THREAD

**Issue by SlayerAnsh** [andromedaprotocol/andromeda.js#82]
When querying bank balance, user has to input denom and address for the wallet he wants to know the balance. However, most of the time user wants to know his wallet balance on the current chain client is connected to. It will be better for user experience if fields for denom and address are preloaded for the current client connected so user can easily check his wallet balance.

<img width="549" alt="image" src="https://github.com/andromedaprotocol/andromeda.js/assets/53444123/7fd2df47-54ad-43b1-bce8-4e1b301939f0">

### Feature Request:
- Add current chain gas fee denom as default value for `bank->balance->denom` field
- Add current wallet address as  default value for `bank->balance->address` field

**Comment by leifasorensen** [comment]
We have added this functionality during some of our auto-completion updates issued in later versions. You can see both the denomination and current wallet auto-fill recommendations in the following screenshots (from ver 0.3.8).

Closing enhancement #82 as integrated.

# Bank Balance Auto Completion
![auto-populate denom](https://github.com/andromedaprotocol/andromeda.js/assets/60895101/950f1de0-97a9-4316-aaa1-26d0be4364ba)
![auto-populate wallet](https://github.com/andromedaprotocol/andromeda.js/assets/60895101/059c04a7-e594-4041-ba0f-84c75f12b0ed)
