### ISSUE TITLE
webapp - Blank Canvas vs Empty Project

### ISSUE THREAD

**Issue by MyronKoch-dev** [andromedaprotocol/andromeda.js#85]
Harmonize the terms "blank canvas" and "empty project" by simply changing the subheader in the Empty Project UI component to "a blank canvas to start from scratch with"
![Screenshot 2023-09-27 at 6 03 26 PM](https://github.com/andromedaprotocol/andromeda.js/assets/137090178/9618f708-27a6-4632-a659-c7770972dd52)

**Comment by leifasorensen** [comment]
Issue is related to webapp. This issue has been replicated in correct web app reporting section. Closing this task.
