### ISSUE TITLE
webapp - give users rules to the naming of components

### ISSUE THREAD

**Issue by MyronKoch-dev** [andromedaprotocol/andromeda.js#86]
when naming components/ados/etc, consider changing the warning "name should be alphanumeric," to "Name must contain only letters, numbers, dashes, and underscores. No spaces allowed." 
![Screenshot 2023-09-27 at 10 18 24 AM](https://github.com/andromedaprotocol/andromeda.js/assets/137090178/543a709a-a4c7-4bff-8f23-c3772efaaa5f)

**Comment by leifasorensen** [comment]
This issue is being closed as it applies to the web app. The issue has been reissued in correct location.
