### ISSUE TITLE
CLI- suggestion - List every CLI command and subcommand when --help is invoked

### ISSUE THREAD

**Issue by MyronKoch-dev** [andromedaprotocol/andromeda.js#87]
List every CLI command and subcommand when --help is invoked. Right now, only the top level is displayed

**Comment by leifasorensen** [comment]
A further review can be performed for help operations, and further information on using help flags can be added to the documentation found at: https://docs.andromedaprotocol.io/andromeda/andromeda-cli/help-and-shortcuts#help-flag

Currently the structure for differences in primary and sub-menu options (that are not commands) are loading base routes on the --help flag. As seen in the screenshot  provided. Currently using the flag without double dashes `help` will trigger the sub command listings related to that command (but are thrown as an error).
# command --help & command help
![ado help sub commands](https://github.com/andromedaprotocol/andromeda.js/assets/60895101/9b9cced4-f2ec-42c8-b1c2-59bc547e3bab)
# command sub command --help
As seen in this screenshot provided adding the `--help` flag on a command (such as `ado create`) returns the commands usage structure and valid flags. In this case it is also returning other sub-commands which might apply to the base command (in this case `ado`)

![ado cmd help](https://github.com/andromedaprotocol/andromeda.js/assets/60895101/cb56b21f-6e35-4884-9b8b-4572c4505e9a)

**Comment by leifasorensen** [comment]
This issue should be resolved in PR #99 and will be released in ver 0.3.9
