### ISSUE TITLE
CLI Bug: using ado create for a cw721 throws errors and loops

### ISSUE THREAD

**Issue by MyronKoch-dev** [andromedaprotocol/andromeda.js#89]
**creating a 721 with no modules throws
"Cannot read properties of undefined (reading 'getCodeId')
Use the --help flag for help"

creating 721 with modules generates an un-quittable loop. 
![Screenshot 2023-09-25 at 10 05 56 AM](https://github.com/andromedaprotocol/andromeda.js/assets/137090178/643fe50e-2134-4b39-8683-27d3536c609a)

**Comment by cowboy0015** [comment]
I tried to create a cw721 with no modules and it was working. Would you mind giving more details to reproduce the bug?
![image](https://github.com/andromedaprotocol/andromeda.js/assets/138406401/f3a0fcf1-99f6-4e47-b12a-2e211ac2b010)

**Comment by leifasorensen** [comment]
I have also confirmed that this issue has been resolved by CLI-0.3.8 (screenshot attached). The original version was not noted, but the lack of the `add owner` field indicates it was an older version.

Closing issue as resolved.
#
![Issue 89](https://github.com/andromedaprotocol/andromeda.js/assets/60895101/bfd69741-1d59-4ba7-bc9f-ebff1888df3d)
