### ISSUE TITLE
Webapp suggestion - clarify warning on the Cw20 Exchange component 

### ISSUE THREAD

**Issue by MyronKoch-dev** [andromedaprotocol/andromeda.js#90]
CW20 exchange ado builder:  it auto-names the token component in 2 places (in the CW20 component's name, then again under the Cw20 Exchange's Token Address.  However...

When path isn't changed, an error warning appears on the Cw20 Exchange component saying "not a valid local vfs path," but perhaps it should say something like "change this to the address of the cw20 token ADO you're selling." 

![Screenshot 2023-09-28 at 9 29 06 PM](https://github.com/andromedaprotocol/andromeda.js/assets/137090178/95d9df42-ac8d-477b-ac1f-49d3a2ce6d6e)
![Screenshot 2023-09-28 at 9 29 16 PM](https://github.com/andromedaprotocol/andromeda.js/assets/137090178/e644c841-8f4a-4c1a-bf84-174ef6c46fc9)

**Comment by leifasorensen** [comment]
This issue is being closed as it applies to the web app. The issue has been reissued in correct location.
