### ISSUE TITLE
Webapp Bug: ./tokens warning “not a valid local vfs path” in CW20 exchange ADO, unless worked around

### ISSUE THREAD

**Issue by MyronKoch-dev** [andromedaprotocol/andromeda.js#91]
BUG REPORT
In ADO block builder, 
click CW20 exchange template > scroll to bottom
"CW20 exchange" ADO’s “Token address” field autopopulates with ./tokens, but warns “not a valid local vfs path.”
Engaging the dropdown menu and selecting ./tokens from the list has no effect, 
BUT
Inserting another autopopulated option, then erasing it, then choosing ./tokens WORKS
![Screenshot 2023-10-09 at 12 06 15 AM](https://github.com/andromedaprotocol/andromeda.js/assets/137090178/86510220-35d1-49f7-9915-06ad7269818d)

**Comment by leifasorensen** [comment]
Issue is related to webapp. This issue has been replicated in correct web app reporting section. Closing this task.
