### ISSUE TITLE
Wallet Encoding Conflicts with Wallet Generation

### ISSUE THREAD

**Issue by leifasorensen** [andromedaprotocol/andromeda.js#95]
**Describe the bug**
It needs to be confirmed, but it appears that there may be an encoding conflict when generating a terra wallet address in the CLI. Generated addresses do not appear to be consistent with the addresses which are seen in Keplr and TerraStation for the same key. 

This is likely due to a variance in the encoding scheme used. The CLI employs bech32 for address generation, and is likely not the same as found in previously mentioned sources. A review of the encoding schema for those sources would confirm this assumption.

This can produce some interesting conflicts, as some functionality is still operable with different addresses, but likely creates conflicts in permission assignments, block explorer references, and potentially fund allocation retrievals.

**Error Code**
N/A

**To Reproduce**
1. Generate a new wallet and address for Terra using CLI (retaining key phrase)
2.Add this wallet (using the retained key phrase) to Keplr and or TerraStation
3. Confirm that the wallet addresses do or do not match across each platform
4. Try the inverse of this process using `wallet add --recover`

**Expected behavior**
Generation of wallet addresses, no matter which source, (from those mentioned) should be consistent.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Mac OS Version 14.2.1 
 - Version CLI-0.3.8
 - Chain Terra

**Additional context**
Closing a previous Issue reported which is believed to be related.

**Comment by daniel-wehbe** [comment]
Tested importing wallet from CLI to keplr and station and the reverse. All addresses matched. Will close the issue.

**Comment by daniel-wehbe** [comment]
CLI version: Version: 0.3.8
